import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'

export default function HomePage() {
  return (
    <div className="flex-1 flex flex-col items-center justify-center p-6 text-center space-y-8">
      <div className="space-y-4">
        <h1 className="text-5xl font-bold">Welcome to NutriAI</h1>
        <p className="text-xl text-muted-foreground max-w-2xl">
          Your AI-powered nutrition assistant. Generate personalized recipes based on your
          dietary preferences and nutritional goals.
        </p>
      </div>

      <div className="flex gap-4">
        <Link to="/generate">
          <Button size="lg">Generate Recipe</Button>
        </Link>
        <Link to="/recipes">
          <Button size="lg" variant="outline">
            View Saved Recipes
          </Button>
        </Link>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mt-12">
        <div className="p-6 border rounded-lg">
          <h3 className="text-lg font-semibold mb-2">AI-Powered</h3>
          <p className="text-sm text-muted-foreground">
            Get recipe suggestions generated by advanced AI based on your preferences
          </p>
        </div>
        <div className="p-6 border rounded-lg">
          <h3 className="text-lg font-semibold mb-2">Personalized</h3>
          <p className="text-sm text-muted-foreground">
            Recipes tailored to your nutritional goals and dietary restrictions
          </p>
        </div>
        <div className="p-6 border rounded-lg">
          <h3 className="text-lg font-semibold mb-2">Save & Track</h3>
          <p className="text-sm text-muted-foreground">
            Save your favorite recipes and track your nutritional intake
          </p>
        </div>
      </div>
    </div>
  )
}
