# Generated by Django 4.2.11 on 2025-10-14 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ingredientes_texto', models.TextField(help_text='Comma-separated list of ingredients')),
                ('pasos_texto', models.TextField(help_text='Numbered steps separated by periods')),
                ('calorias', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('proteinas', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohidratos', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('grasas', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_min', models.PositiveIntegerField(help_text='Preparation time in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-created_at'],
            },
        ),
    ]
