# Generated by Django 4.2.11 on 2025-10-18 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_rename_fields_to_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday of the week (ISO 8601 week date)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0 = Monday, 6 = Sunday')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('is_leftover', models.BooleanField(default=False, help_text='True if this meal reuses leftovers from another meal')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='recipes.mealplan')),
                ('original_meal_slot', models.ForeignKey(blank=True, help_text='The original meal this is a leftover from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftover_uses', to='recipes.mealslot')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_slots', to='recipes.receta')),
            ],
            options={
                'verbose_name': 'Meal Slot',
                'verbose_name_plural': 'Meal Slots',
                'ordering': ['meal_plan', 'day_of_week', 'meal_type'],
                'unique_together': {('meal_plan', 'day_of_week', 'meal_type')},
            },
        ),
    ]
