# Generated by Django 4.2.11 on 2025-10-18 03:34

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_mealplan_mealslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.IntegerField(db_index=True, help_text='USDA FoodData Central ID', unique=True)),
                ('description', models.CharField(db_index=True, help_text='Food name/description', max_length=500)),
                ('brand_owner', models.CharField(blank=True, max_length=200)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='UPC/GTIN barcode', max_length=20)),
                ('ingredients', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('serving_size', models.FloatField(blank=True, help_text='Serving size amount', null=True)),
                ('serving_size_unit', models.CharField(blank=True, help_text='Serving size unit (g, ml, etc.)', max_length=20)),
                ('calories', models.IntegerField(blank=True, help_text='Calories per serving', null=True)),
                ('protein', models.FloatField(blank=True, help_text='Protein in grams per serving', null=True)),
                ('carbs', models.FloatField(blank=True, help_text='Carbohydrates in grams per serving', null=True)),
                ('fats', models.FloatField(blank=True, help_text='Total fats in grams per serving', null=True)),
                ('fiber', models.FloatField(blank=True, help_text='Fiber in grams per serving', null=True)),
                ('sugars', models.FloatField(blank=True, help_text='Sugars in grams per serving', null=True)),
                ('sodium', models.FloatField(blank=True, help_text='Sodium in mg per serving', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('quantity_grams', models.FloatField(help_text='Quantity in grams', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('calories', models.IntegerField(help_text='Calculated calories for this entry')),
                ('protein', models.FloatField(help_text='Calculated protein in grams')),
                ('carbs', models.FloatField(help_text='Calculated carbs in grams')),
                ('fats', models.FloatField(help_text='Calculated fats in grams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='recipes.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Log',
                'verbose_name_plural': 'Food Logs',
                'ordering': ['-date', 'meal_type', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['description'], name='recipes_foo_descrip_6f6793_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['fdc_id'], name='recipes_foo_fdc_id_30999a_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['user', 'date'], name='recipes_foo_user_id_59db4b_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['date'], name='recipes_foo_date_8cea46_idx'),
        ),
    ]
