# Generated by Django 4.2.11 on 2025-10-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little or no exercise)'), ('lightly_active', 'Lightly Active (exercise 1-3 days/week)'), ('moderately_active', 'Moderately Active (exercise 3-5 days/week)'), ('very_active', 'Very Active (exercise 6-7 days/week)'), ('extremely_active', 'Extremely Active (physical job or training twice/day)')], default='', help_text='Activity level', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.TextField(blank=True, help_text="Food allergies (e.g., 'peanuts, shellfish, dairy')"),
        ),
        migrations.AddField(
            model_name='profile',
            name='cooking_skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Cooking skill level', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='cuisine_preferences',
            field=models.TextField(blank=True, help_text="Preferred cuisines (e.g., 'Italian, Mexican, Asian')"),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_calorie_target',
            field=models.IntegerField(blank=True, help_text='Daily calorie target (kcal)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_carbs_target',
            field=models.IntegerField(blank=True, help_text='Daily carbohydrates target (grams)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_fats_target',
            field=models.IntegerField(blank=True, help_text='Daily fats target (grams)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_protein_target',
            field=models.IntegerField(blank=True, help_text='Daily protein target (grams)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dislikes',
            field=models.TextField(blank=True, help_text="Disliked ingredients (e.g., 'mushrooms, cilantro')"),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', help_text='Gender', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.IntegerField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spice_preference',
            field=models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('spicy', 'Spicy')], default='mild', help_text='Spice preference', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('maintain_weight', 'Maintain Weight'), ('gain_muscle', 'Gain Muscle'), ('improve_health', 'Improve Health')], default='', help_text='Primary nutritional goal', max_length=20),
        ),
    ]
