# Generated by Django 4.2.11 on 2025-10-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_activity_level_profile_age_profile_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_ingredients',
            field=models.TextField(blank=True, help_text="Ingredients you currently have in your pantry (e.g., 'eggs, tomatoes, pasta, cheese')"),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_ingredients',
            field=models.TextField(blank=True, help_text="Ingredients you like to use regularly (e.g., 'chicken, rice, broccoli, olive oil')"),
        ),
    ]
