# Generated by Django 4.2.11 on 2025-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_available_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.TextField(blank=True, help_text='Primary nutritional goal'),
        ),
    ]
